name = "protoflyer"
id = 22105
vendor = "px4"
model = "fmu-v3"
px4_version = "v0.0.0"
px4_commit = "75e4047f2aaaf86d943d73cf9965b45987e61d96" # main (Jun 13)
custom_fw_version = "0.1.0"
components = ["radiomaster_tx16s"]
