#!/bin/sh
#
# @name EOLab Phoenix
#
# @type Hexarotor x
# @class Copter
#
# @output Motor1 motor 1
# @output Motor2 motor 2
# @output Motor3 motor 3
# @output Motor4 motor 4
# @output Motor5 motor 5
# @output Motor6 motor 6
#
# @maintainer Harley Lara <contact@harleylara.com>
# @url https://drones.eolab.de/phoenix/README.html
#

. ${R}etc/init.d/rc.mc_defaults


# MAV_TYPE_HEXAROTOR 13
param set-default MAV_TYPE 13

param set-default CA_ROTOR_COUNT 6
param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY 0.5
param set-default CA_ROTOR0_KM -0.05
param set-default CA_ROTOR1_PX 0
param set-default CA_ROTOR1_PY -0.5
param set-default CA_ROTOR2_PX 0.43
param set-default CA_ROTOR2_PY -0.25

param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.43
param set-default CA_ROTOR3_PY 0.25
param set-default CA_ROTOR4_PX 0.43
param set-default CA_ROTOR4_PY 0.25
param set-default CA_ROTOR5_PX -0.43
param set-default CA_ROTOR5_PY -0.25
param set-default CA_ROTOR5_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106

################
# RADIO
################

# enable MAVLink in TELEM1
param set-default MAV_0_CONFIG 101 # https://docs.px4.io/main/en/advanced_config/parameter_reference.html#MAV_0_CONFIG
# disable MAVLink in TELEM2 to prevent problems with CRSF (see param RC_CRSF_PRT_CFG)
param set-default MAV_1_CONFIG 0

# select CRSF as RC protocol
param set-default RC_INPUT_PROTO 6
# enable CRSF input in TELEM2
param set-default RC_CRSF_PRT_CFG 102 # https://docs.px4.io/main/en/advanced_config/parameter_reference.html#RC_CRSF_PRT_CFG

################################
# Parameters Radiomaster TX16S
################################

param set-default RC_CHAN_CNT 8

# channel mapping according to our conventions (Mode 2): https://drones.eolab.de/transmitter.html
param set-default RC_MAP_ROLL 1
param set-default RC_MAP_PITCH 2
param set-default RC_MAP_THROTTLE 3
param set-default RC_MAP_YAW 4
param set-default RC_MAP_OFFB_SW 5
param set-default RC_MAP_FLTMODE 6
# TODO:
# MAKE the KILL SWITCH UNIQUE (if the position of the switch return it should remains off)
param set-default RC_MAP_KILL_SW 8

# we are using all the RCX channel with the default values:
# MAX: 2000
# MIN: 1000
# TRIM: 1500
param set-default RC6_MAX 2000
param set-default RC6_MIN 1000
param set-default RC6_TRIM 1500

# flight modes setup, as described in https://drones.eolab.de/transmitter.html#flight-modes
param set-default COM_FLTMODE1 2 # Position Mode

