#!/bin/sh
#
# @name EOLab Phoenix
#
# @type Hexarotor x
# @class Copter
#
# @output Motor1 motor 1
# @output Motor2 motor 2
# @output Motor3 motor 3
# @output Motor4 motor 4
# @output Motor5 motor 5
# @output Motor6 motor 6
#
# @maintainer Harley Lara <contact@harleylara.com>
# @url https://drones.eolab.de/phoenix/README.html
#

. ${R}etc/init.d/rc.mc_defaults
. ${R}etc/init.d/rc.radiomaster_tx16s # radio params

# MAV_TYPE_HEXAROTOR 13
param set-default MAV_TYPE 13

#####################################
# FMU placement and orientation
#####################################

param set-default EKF2_IMU_POS_X 0.10
param set-default EKF2_IMU_POS_Y 0
param set-default EKF2_IMU_POS_Z 0

#####################################
# Actuators
#####################################

param set-default CA_ROTOR_COUNT 6

param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY 0.58
param set-default CA_ROTOR0_KM -0.05
param set-default CA_ROTOR1_PX 0
param set-default CA_ROTOR1_PY -0.58
param set-default CA_ROTOR2_PX 0.51
param set-default CA_ROTOR2_PY -0.29


param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.51
param set-default CA_ROTOR3_PY 0.29
param set-default CA_ROTOR4_PX 0.51
param set-default CA_ROTOR4_PY 0.29
param set-default CA_ROTOR5_PX -0.51
param set-default CA_ROTOR5_PY -0.29
param set-default CA_ROTOR5_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106

#####################################
# ESC Calibration
#####################################

param set-default PWM_MAIN_MIN1 1150
param set-default PWM_MAIN_MAX1 1900

param set-default PWM_MAIN_MIN2 1150
param set-default PWM_MAIN_MAX2 1900

param set-default PWM_MAIN_MIN3 1150
param set-default PWM_MAIN_MAX3 1900

param set-default PWM_MAIN_MIN4 1150
param set-default PWM_MAIN_MAX4 1900

param set-default PWM_MAIN_MIN5 1150
param set-default PWM_MAIN_MAX5 1900

param set-default PWM_MAIN_MIN6 1150
param set-default PWM_MAIN_MAX6 1900

#####################################
## Sensors
#####################################

# Range finder sensor
# (phoenix) is equiped with the SF11/C see: https://lightwarelidar.com/shop/sf11-c-100-m/
# to this parameter to work make sure the I2C protocol is correlty set, see: https://docs.px4.io/main/en/sensor/sfxx_lidar.html#i2c-setup
param set-default SENS_EN_SF1XX 3

param set-default GPS_2_CONFIG 202 # note: the GPS2 physical port is map to TELEM4 internally, see: https://docs.px4.io/v1.11/en/flight_controller/pixhawk-2.html#serial_ports
param set-default SER_GPS2_BAUD 0 # Baudrate Auto

#####################################
## Battery
#####################################
param set-default BAT1_SOURCE 0
param set-default BAT1_N_CELLS 6
param set-default BAT1_V_CHARGED 4.02
param set-default BAT1_V_EMPTY 3.7
param set-default BAT1_V_DIV 12.05273533
param set-default BAT1_CAPACITY 11000
# TODO: 
# - BAT1_R_INTERNAL
