name: Generate Firmwares and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Run generation script
        run: |
          chmod +x ./build.sh
          ./build.sh all
