name: Generate Firmwares and Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt -y install gcc-arm-none-eabi python3-pip
      - name: Quick check
        run: pip --version
      - name: Install Python tool (editable mode)
        run: |
          pip install -e .
      - name: Configure Git committer
        run: |
          git config --global user.email "github-actions[bot]"
          git config --global user.name "GitHub Actions Bot"
      - name: Build Firmwares
        run: |
          DEBUG=1 eolab_drones build_all --type firmware
      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          assets: '*.px4'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.px4"
          tag_name: latest
          name: Latest Firmwares
          draft: false
          body: "This is an auto-generated set of our latest firmwares for all our drones"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
