name: Test eas_px4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull latest image explicitly
        run: docker pull ghcr.io/eolab-hsrw/easy-px4:ubuntu-22.04

      - name: Run build
        run: docker run --rm ghcr.io/eolab-hsrw/easy-px4:ubuntu-22.04 -e DEBUG=1 easy_px4 build --type firmware --path /home/easy/easy-px4/demos/protoflyer/ --comps /home/easy/easy-px4/demos/components/

